spring.application.name=pet-api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/petdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration