spring.application.name=pet-api
server.port=8080
spring.profiles.active=dev

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/petdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000

spring.mvc.problemdetails.enabled=true
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.default-page-size=20

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

spring.data.mongodb.uri=mongodb://localhost:27017/petdb
spring.data.mongodb.auto-index-creation=true

spring.kafka.bootstrap-servers=localhost:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

resilience4j.circuitbreaker.instances.kafka-publisher.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafka-publisher.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kafka-publisher.sliding-window-size=5

resilience4j.bulkhead.instances.kafka-publisher.max-concurrent-calls=10
resilience4j.bulkhead.instances.kafka-publisher.max-wait-duration=0ms

resilience4j.retry.instances.pet-db.max-attempts=3
resilience4j.retry.instances.pet-db.wait-duration=200ms
resilience4j.retry.instances.pet-db.retry-exceptions=org.springframework.dao.TransientDataAccessException,org.springframework.dao.RecoverableDataAccessException

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.sampling.probability=1.0
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=pet-api
info.app.version=0.0.1