apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: pet-api
data:
  DB_HOST: "mysql-service"
  REDIS_HOST: "redis-service"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_PROFILES_ACTIVE: "prod"
