apiVersion: v1
kind: ConfigMap
metadata:
  name: pet-api-config
  namespace: pet-api
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/petdb"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_URI: "mongodb://mongo-service:27017/petdb"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin-service:9411/api/v2/spans"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
